### ISSUE TITLE
Design Implementation Error.

### ISSUE THREAD

**Issue by asis-parajuli** [wdr-data/django-emoji-picker#4]
After I install the the library as pip install django-emoji-picker
and used in the model class as 

from django import forms
from emoji_picker.widgets import EmojiPickerTextInputAdmin, EmojiPickerTextareaAdmin

class TweetModelForm(forms.ModelForm):
    content = forms.CharField(widget=EmojiPickerTextareaAdmin) 

And I got very awkward design like this screenshot.

How to resolve this issue.
![Screenshot (78)](https://user-images.githubusercontent.com/60426026/77289315-d8540000-6d01-11ea-8776-d310e27ea799.png)

**Comment by tablefiller** [comment]
same here. I'm using bootstrap. Is there way to know if there's a conflict with classes? tks

**Comment by mahrous-amer** [comment]
you need to have this `{{ form.media }}` in your template head 
Reference this:
https://stackoverflow.com/questions/1558533/django-widget-media-doesnt-work
https://docs.djangoproject.com/en/3.1/ref/forms/widgets/

**Comment by asis-parajuli** [comment]
Within the template html file we should include the 
{% block extrahead %}
{{ form.media }}
{% endblock %} 
as shown below
![image](https://user-images.githubusercontent.com/60426026/90467353-bdac7880-e133-11ea-8fe1-b6bdf5885ced.png)

And other things are the same like this
![image](https://user-images.githubusercontent.com/60426026/90467453-f9474280-e133-11ea-99b4-bc5a11b5174d.png)
